version="2.0"

[project]
name="{{ cookiecutter.project_name }}"
author="{{ cookiecutter.author_name }}"
environment="{{ cookiecutter.environment }}"

[db]
postgres_user="{{ cookiecutter.postgres_user }}"
postgres_pass="{{ cookiecutter.postgres_pass }}"
postgres_host="{{ cookiecutter.postgres_host }}"
postgres_port={{ cookiecutter.postgres_port }}
postgres_dbname="{{ cookiecutter.postgres_dbname }}"

[prefect]
server_endpoint="http://prefect.apps.{{ cookiecutter.server_name }}"
api_server="http://prefect.apps.{{ cookiecutter.server_name }}/graphql/"
docker_registry="docker-registry.{{ cookiecutter.server_name }}"

[mlflow]
tracking_url="http://mlflow.apps.{{ cookiecutter.server_name }}/"
artifacts_aws_access_key_id="{{ cookiecutter.mlflow_artifacts_aws_access_key_id }}"
artifacts_aws_secret_access_key="{{ cookiecutter.mlflow_artifacts_aws_secret_access_key }}"
artifacts_s3_endpoint_url="{{ cookiecutter.mlflow_artifacts_s3_endpoint_url }}"
