[project]
name="{{ cookiecutter.project_name }}"
author="{{ cookiecutter.author_name }}"
environment="{{ cookiecutter.environment }}"

[db]
postgres_user="{{ cookiecutter.postgres_user }}"
postgres_pass="{{ cookiecutter.postgres_pass }}"
postgres_host="{{ cookiecutter.postgres_host }}"
postgres_port={{ cookiecutter.postgres_port }}
postgres_dbname="{{ cookiecutter.postgres_dbname }}"

[prefect]
server_endpoint="http://prefect.apps.{{ cookiecutter.server_name }}"
api_server="http://prefect.apps.{{ cookiecutter.server_name }}/graphql/"
docker_registry="https://docker-registry.{{ cookiecutter.server_name }}/"

[mlflow]
tracking_url="http://mlflow.apps.{{ cookiecutter.server_name }}/"
