[project]
project_name="{{ cookiecutter.repo_name }}"

[config]
POSTGRES_USER="archimedes_dev@archimedes-dev"
POSTGRES_PASS="<PGPASS>"
POSTGRES_HOST="archimedes-dev.postgres.database.azure.com"
POSTGRES_PORT="5432"
POSTGRES_DBNAME="archimedes"