[project]
project_name = {{ cookiecutter.repo_name }}

[deploy]

[config]
    POSTGRES_USER = "archimedes_dev@archimedes-dev"
    POSTGRES_PASS = ""
    POSTGRES_HOST = "archimedes-dev.postgres.database.azure.com"
    POSTGRES_PORT = "5432"
    POSTGRES_DBNAME = "archimedes"